### PR TITLE
feat : Added cart page

### PR DESCRIPTION
**Pull request by BalajiHarinath**
Added the Cart page for the Ecommerce app. Please review

### CODE REVIEW

**Comment by vrx29** [comment]
Screenshot 2022-02-06 at 8 47 22 PM

While scrolling your navbar is not fixed it's going up and order details are fixed. Try to fix your navbar too.

**Review by ArjunJunna — APPROVED** [review]
You can decrease the height of nav bar by a bit.

**Review by anik31 — APPROVED** [review]
LGTM

**Comment by BalajiHarinath** [comment]
> Screenshot 2022-02-06 at 8 47 22 PM
> 
> While scrolling your navbar is not fixed it's going up and order details are fixed. Try to fix your navbar too.

Sure. Thanks for pointing this out. Will fix the nav bar too.

**Comment by BalajiHarinath** [comment]
> Screenshot 2022-02-06 at 8 47 22 PM
> 
> While scrolling your navbar is not fixed it's going up and order details are fixed. Try to fix your navbar too.

I have fixed this issue and I have merged.

**Pull request merged**
